[Resolve]
DNS=127.0.0.1
DNSSEC=yes
DNSStubListener=no
# Delegated to Pi-Hole or other local resolver
Cache=no
# Disable link-local name resolution
LLMNR=no
# Avahi daemon handles mDNS
MulticastDNS=no
# Fallback DNS servers
FallbackDNS=8.8.8.8 9.9.9.9
